#!/bin/bash

progdir="$(dirname "$0")"

if [ -f "$progdir/cpuconfig.cfg" ]; then
    . "$progdir/cpuconfig.cfg"
elif [ -f /userdata/cpuconfig.cfg ]; then
    . /userdata/cpuconfig.cfg
fi

echo $CPU_GOVERNOR > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
echo $CPU_MAX > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
echo $CPU_MIN > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
echo $CPU_0 > /sys/devices/system/cpu/cpu0/online
echo $CPU_1 > /sys/devices/system/cpu/cpu1/online
echo $CPU_2 > /sys/devices/system/cpu/cpu2/online
echo $CPU_3 > /sys/devices/system/cpu/cpu3/online
echo $GPU_GOVERNOR > /sys/class/devfreq/dmc/governor

RA_DIR=$(dirname "$0")/../../RetroArch32
cd $RA_DIR
HOME=$RA_DIR
export LD_LIBRARY_PATH="$HOME/lib:$LD_LIBRARY_PATH"

get_connected_audio_bt_mac() {
    for mac in $(bluetoothctl devices | awk '{print $2}'); do
        if bluetoothctl info "$mac" | grep -q "Connected: yes"; then
            name=$(bluetoothctl info "$mac" | grep "Name" | cut -d ' ' -f2-)
            icon=$(bluetoothctl info "$mac" | grep "Icon" | awk '{print $2}')
            if echo "$name" | grep -iqE "headset|speaker|audio|earbud|headphone"; then
                echo "$mac"
                return 0
            fi
            if [[ "$icon" == "audio-headset" || "$icon" == "audio-card" || "$icon" == "audio-headphones" ]]; then
                echo "$mac"
                return 0
            fi
        fi
    done
    return 1
}

mac=$(get_connected_audio_bt_mac)
ASOUND_CONF="$HOME/.asoundrc"

if [ -n "$mac" ]; then
    cat > "$ASOUND_CONF" <<EOF
pcm.!default {
    type plug
    slave.pcm {
        type bluealsa
        device "$mac"
        profile "a2dp"
    }
}
EOF
else
    if [ -f "$ASOUND_CONF" ]; then
        rm "$ASOUND_CONF"
    fi
fi

$RA_DIR/retroarch -v $NET_PARAM -L $RA_DIR/.config/retroarch/cores/$2_libretro.so "$1" 2>&1 | tee -a ./log.txt

echo ondemand > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
echo 1008000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
echo 1 > /sys/devices/system/cpu/cpu0/online
echo 1 > /sys/devices/system/cpu/cpu1/online
echo 0 > /sys/devices/system/cpu/cpu2/online
echo 0 > /sys/devices/system/cpu/cpu3/online

